# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file
extra_config_files: /etc/xivo-ctid/conf.d/
debug: false
foreground: false
dird:
  host: localhost
  port: 9489
  version: 0.1
bus:
  exchange_name: xivo-cti
  exchange_type: direct
  exchange_durable: true
  binding_key: call_form_result
status_notifier:
  exchange_name: xivo-status-updates
  exchange_type: direct
  exchange_durable: True
  routing_keys:
    user: status.user
    endpoint: status.endpoint
db_uri: postgresql://asterisk:proformatique@localhost/asterisk
